default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: secret
  timeout: 5000
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *default
  database: bglmautam_development

test:
  <<: *default
  database: bglmautam_test