development:
  adapter: postgresql
  encoding: unicode
  database: bglmautam_development
  pool: 5
  username:
  password:
  timeout: 5000
  port: 5432
 
test:
  adapter: postgresql
  encoding: unicode
  database: bglmautam_test
  pool: 5
  username: 
  password:
  timeout: 5000